"""Severity, exceptionability, and rule ID enumerations."""

from enum import StrEnum


class Severity(StrEnum):
    """Finding severity levels."""

    ERROR = "ERROR"
    WARNING = "WARNING"
    SUPPRESS = "SUPPRESS"


class Exceptionability(StrEnum):
    """Exception governance classes."""

    UNCONDITIONAL = "UNCONDITIONAL"
    STANDARD = "STANDARD"
    RELAXED = "RELAXED"
    TRANSPARENT = "TRANSPARENT"


class GovernancePath(StrEnum):
    """Governance path for exception grants."""
    STANDARD = "standard"
    EXPEDITED = "expedited"


class RuleId(StrEnum):
    """Rule identifiers — canonical and pseudo-rule-IDs.

    Member names use underscores; string values use hyphens per
    the spec's SARIF format. All IDs that appear as Finding.rule_id
    must be members of this enum.
    """

    # Canonical rules (Python binding)
    PY_WL_001 = "PY-WL-001"
    PY_WL_002 = "PY-WL-002"
    PY_WL_003 = "PY-WL-003"
    PY_WL_004 = "PY-WL-004"
    PY_WL_005 = "PY-WL-005"
    PY_WL_006 = "PY-WL-006"
    PY_WL_007 = "PY-WL-007"
    PY_WL_008 = "PY-WL-008"
    PY_WL_009 = "PY-WL-009"
    SCN_021 = "SCN-021"
    SUP_001 = "SUP-001"

    # Pseudo-rule-IDs (diagnostic signals, not analysis rules)
    PY_WL_001_GOVERNED_DEFAULT = "PY-WL-001-GOVERNED-DEFAULT"
    PY_WL_001_UNGOVERNED_DEFAULT = "PY-WL-001-UNGOVERNED-DEFAULT"
    WARDLINE_UNRESOLVED_DECORATOR = "WARDLINE-UNRESOLVED-DECORATOR"
    TOOL_ERROR = "TOOL-ERROR"
    GOVERNANCE_REGISTRY_MISMATCH_ALLOWED = "GOVERNANCE-REGISTRY-MISMATCH-ALLOWED"
    GOVERNANCE_RULE_DISABLED = "GOVERNANCE-RULE-DISABLED"
    GOVERNANCE_PERMISSIVE_DISTRIBUTION = "GOVERNANCE-PERMISSIVE-DISTRIBUTION"
    GOVERNANCE_STALE_EXCEPTION = "GOVERNANCE-STALE-EXCEPTION"
    GOVERNANCE_UNKNOWN_PROVENANCE = "GOVERNANCE-UNKNOWN-PROVENANCE"
    GOVERNANCE_RECURRING_EXCEPTION = "GOVERNANCE-RECURRING-EXCEPTION"
    GOVERNANCE_BATCH_REFRESH = "GOVERNANCE-BATCH-REFRESH"
    GOVERNANCE_NO_EXPIRY_EXCEPTION = "GOVERNANCE-NO-EXPIRY-EXCEPTION"
    GOVERNANCE_EXCEPTION_TAINT_DRIFT = "GOVERNANCE-EXCEPTION-TAINT-DRIFT"
    GOVERNANCE_EXCEPTION_LEVEL_STALE = "GOVERNANCE-EXCEPTION-LEVEL-STALE"
    GOVERNANCE_EXCEPTION_SEVERITY_DRIFT = "GOVERNANCE-EXCEPTION-SEVERITY-DRIFT"
    GOVERNANCE_CUSTOM_KNOWN_VALIDATOR = "GOVERNANCE-CUSTOM-KNOWN-VALIDATOR"
    L3_LOW_RESOLUTION = "L3-LOW-RESOLUTION"
    L3_CONVERGENCE_BOUND = "L3-CONVERGENCE-BOUND"
